version: '3'

services:
  caddy_reverse_proxy:
    image: caddy/caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    restart: unless-stopped
    depends_on:
      - sg-portal

  sg-portal:
    container_name: sg-portal
    image: ggoneman/shortsgenie:latest
    env_file:
      - .env.docker
    restart: unless-stopped
    networks:
      - caddy_network

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
