services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "120"
      - "--rolling-restart"
      - "--cleanup"
      - "--debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config.json:/config.json
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sahil@shortsgenie.ai"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--log.level=ERROR"  # Set log level to ERROR
#      - "--log.level=DEBUG"  # Set log level to DEBUG
      #      - "--accesslog=true"    # Enable access logs
      #      - "--accesslog.filePath=/var/log/access.log"
      - "--api.dashboard=true"
      #      - "--api.insecure=true"
      - "--log.maxage=3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`rp.shortsgenie.ai`)||Host(`www.rp.shortsgenie.ai`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/users/users.txt"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      #      - ./traefik/logs:/var/log
      - ./users:/users

  shortsgenie:
    image: ggoneman/shortsgenie:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shortsgenie.rule=Host(`shortsgenie.ai`) || Host(`www.shortsgenie.ai`)"
      - "traefik.http.routers.shortsgenie.entrypoints=websecure"
      - "traefik.http.routers.shortsgenie.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 2
    restart: always
    depends_on:
      - reverse-proxy
    env_file:
      - .env.docker


volumes:
  letsencrypt:
    name: letsencrypt
  traefik:
    name: traefik

