version: '3.7'

services:

  caddy_reverse_proxy:
    image: caddy/caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    restart: always
    depends_on:
      - sg-portal

  sg-portal:
    image: ggoneman/shortsgenie:latest
    pull_policy: always
    restart: always
    networks:
      - caddy_network

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
